apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lagrange.fullname" . }}
  labels:
    {{- include "lagrange.labels" . | nindent 4 }}
stringData:
  appsettings.json: {{- .Values.lagrange.appsettings | toYaml | indent 2 }}
